import { AllowedHostDomainParameter } from "./paramater";

export const AllowedUrlDomain: AllowedHostDomainParameter = {
  "<hallobali>": "https://hallobali.id/",
 // "<daruratmilyader>": "https://daruratmilyader.com/",
  "<ipaymu>": "https://ipaymu.com/",
  "<marketbiz>": "https://marketbiz.net/",
  "<lakujual>": "https://lakujual.id/",
  "<lakustore>": "https://lakustore.id/",
  "<bebaskirim>": "https://bebaskirim.com/",
  "<metodesehat>": "https://www.metodesehat.com/",
  "<resellr>": "https://resellr.id/",
  "<sarungindonesia-com>": "https://sarungindonesia.com/",
  "<sarungindonesia-co-id>": "https://sarungindonesia.co.id/",
  "<putusdijalan>": "https://linktr.ee/putusdijalan/",
  "<terapiholistinawasena>": "https://nawasenacare.com/",
  "<sikopin>": "https://sikopin.com",
  "<manhattancool>": "https://manhattancool.id/",
  "<langfit>": "https://langfit.id/",
  "<aftergraph>": "https://aftergraphs.com/",
  "<nenavin>": "https://nenavin.com/",
  "<salimamemorialpark>": "https://propertilogi.com/",
  "<sentramukena>": "https://sentramukena.id/",
  "<rumahakrilik>": "https://rumahakrilik.my.id/",
  "<penerbituwais>": "https://penerbit.uwais.net/",
  "<ote>": "https://servicesofadijogja.com/",
  "<topkursus>": "https://topkursus.com/",
  "<flubaanaba>": "https://linktr.ee/Fluba.id",
  "<gizidat>": "https://mygizidat.com/",
  "<karetjembatan>": "https://karetkonstruksi.com/",
  "<payaman>": "https://payamandigital.com/",
};

export const AllowedHostDomain: AllowedHostDomainParameter = {
  "<hallobali>": "hallobali.id",
 // "<daruratmilyader>": "daruratmilyader.com",
  "<ipaymu>": "ipaymu.com",
  "<marketbiz>": "marketbiz.net",
  "<lakujual>": "lakujual.id",
  "<lakustore>": "lakustore.id",
  "<bebaskirim>": "bebaskirim.com",
  "<metodesehat>": "www.metodesehat.com",
  "<resellr>": "resellr.id",
  "<sarungindonesia-com>": "sarungindonesia.com",
  "<sarungindonesia-co-id>": "sarungindonesia.co.id",
  "<putusdijalan>": "linktr.ee",
  "<terapiholistinawasena>": "https://nawasenacare.com/",
  "<sikopin>": "https://sikopin.com",
  "<manhattancool>": "https://manhattancool.id/",
  "<langfit>": "https://langfit.id/",
  "<aftergraph>": "https://aftergraphs.com/",
  "<nenavin>": "https://nenavin.com/",
  "<salimamemorialpark>": "https://propertilogi.com/",
  "<sentramukena>": "https://sentramukena.id/",
  "<rumahakrilik>": "https://rumahakrilik.my.id/",
  "<penerbituwais>": "https://penerbit.uwais.net/",
  "<ote>": "https://servicesofadijogja.com/",
  "<topkursus>": "https://topkursus.com/",
  "<flubaanaba>": "https://linktr.ee/Fluba.id",
  "<gizidat>": "https://mygizidat.com/",
  "<karetjembatan>": "https://karetkonstruksi.com/",
  "<payaman>": "https://payamandigital.com/",
};

export const AllowedUrlDomainComplete: AllowedHostDomainParameter = {
  "<hallobali>": "https://hallobali.id/",
  //"<daruratmilyader>": "https://daruratmilyader.com/",
  "<ipaymu>": "https://ipaymu.com/",
  "<marketbiz>": "https://marketbiz.net/",
  "<lakujual>": "https://lakujual.id/",
  "<lakustore>": "https://lakustore.id/",
  "<bebaskirim>": "https://bebaskirim.com/",
  "<metodesehat>": "https://www.metodesehat.com/",
  "<resellr>": "https://resellr.id/",
  "<sarungindonesia-com>": "https://sarungindonesia.com/",
  "<sarungindonesia-co-id>": "https://sarungindonesia.co.id/",
  "<putusdijalan>": "https://linktr.ee/putusdijalan/",
  "<terapiholistinawasena>": "https://nawasenacare.com/",
  "<sikopin>": "https://sikopin.com",
  "<manhattancool>": "https://manhattancool.id/",
  "<langfit>": "https://langfit.id/",
  "<aftergraph>": "https://aftergraphs.com/",
  "<nenavin>": "https://nenavin.com/",
  "<salimamemorialpark>": "https://propertilogi.com/",
  "<sentramukena>": "https://sentramukena.id/",
  "<rumahakrilik>": "https://rumahakrilik.my.id/",
  "<penerbituwais>": "https://penerbit.uwais.net/",
  "<ote>": "https://servicesofadijogja.com/",
  "<topkursus>": "https://topkursus.com/",
  "<flubaanaba>": "https://linktr.ee/Fluba.id",
  "<gizidat>": "https://mygizidat.com/",
  "<karetjembatan>": "https://karetkonstruksi.com/",
  "<payaman>": "https://payamandigital.com/",
};

export const AllowedHostDomainComplete: AllowedHostDomainParameter = {
  "<hallobali>": "hallobali.id",
  //"<daruratmilyader>": "daruratmilyader.com",
  "<ipaymu>": "ipaymu.com",
  "<marketbiz>": "marketbiz.net",
  "<lakujual>": "lakujual.id",
  "<lakustore>": "lakustore.id",
  "<bebaskirim>": "bebaskirim.com",
  "<metodesehat>": "www.metodesehat.com",
  "<resellr>": "resellr.id",
  "<sarungindonesia-com>": "sarungindonesia.com",
  "<sarungindonesia-co-id>": "sarungindonesia.co.id",
  "<putusdijalan>": "linktr.ee",
  "<terapiholistinawasena>": "https://nawasenacare.com/",
  "<sikopin>": "https://sikopin.com",
  "<manhattancool>": "https://manhattancool.id/",
  "<langfit>": "https://langfit.id/",
  "<aftergraph>": "https://aftergraphs.com/",
  "<nenavin>": "https://nenavin.com/",
  "<salimamemorialpark>": "https://propertilogi.com/",
  "<sentramukena>": "https://sentramukena.id/",
  "<rumahakrilik>": "https://rumahakrilik.my.id/",
  "<penerbituwais>": "https://penerbit.uwais.net/",
  "<ote>": "https://servicesofadijogja.com/",
  "<topkursus>": "https://topkursus.com/",
  "<flubaanaba>": "https://linktr.ee/Fluba.id",
  "<gizidat>": "https://mygizidat.com/",
  "<karetjembatan>": "https://karetkonstruksi.com/",
  "<payaman>": "https://payamandigital.com/",
};

export const AtLeastThisUrlAppear = "https://hallobali.id/"